gem 'minitest', '~> 5.2'
require 'simplecov'; SimpleCov.start
require 'minitest/autorun'
require 'minitest/mock'
require 'minitest/pride'
require 'stringio'
require_relative '../lib/cli'
require_relative '../lib/data_cleaner'
require_relative '../lib/attendee'
require_relative '../lib/attendee_repository'
require_relative '../lib/attendee_queue'
require_relative '../lib/input_parser'
require_relative '../lib/printer'
require_relative '../lib/help'
